spring.application.name=auth-service
server.port=${AUTH_SERVICE_PORT}
spring.data.mongodb.uri=${AUTH_MONGO_URI}
spring.data.mongodb.database=${AUTH_MONGO_DB}
auth.service.aes.secret.key=${GRAPES_AES_KEY}
sendgrid.api.key=${GRAPES_SENDGRIP_API_SECRET}
twilio.api.key=${GRAPES_TWILIO_API_SECRET}
twilio.account.sid=${GRAPES_TWILIO_SID}
twilio.from.number=${TWILIO_FROM_NUMBER}
company.mail=${COMPANY_MAIL}
auth.service.jwt.secret.key=${GRAPES_JWT_SECRET_KEY}
auth.service.jwt.expiration.time=${TOKEN_EXPIRATION}


spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.timeout=5000ms
