server.port=8091

spring.application.name=auth-service
spring.data.mongodb.uri=mongodb://root:SparringMASI!@localhost:27017/?authSource=admin
spring.data.mongodb.database=db_auth
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
auth.service.aes.secret.key=${GRAPES_AES_KEY}
sendgrid.api.key=${GRAPES_TWILIO_API_SECRET}
company.mail=cameron.noupoue@student.hepl.be
auth.service.jwt.secret.key=${GRAPES_JWT_SECRET_KEY}