version: '3.8'

services:
### DATABASES
  mariadb:
    build: ./docker/mariadb
    env_file: .env
    image: grapeshub/mariadb-grapes:latest
    container_name: grapes-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: SparringMASI!
      MARIADB_USER: root
      MARIADB_PASSWORD: SparringMASI!
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mariadb/volumes/mariadb_data:/var/lib/mysql

  mongodb-primary:
    build: ./docker/mongodb
    env_file: .env
    image: grapeshub/mongodb-grapes:latest
    container_name: grapes-mongodb-primary
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: SparringMASI!
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_primary:/data/db
      - ./docker/mongodb/mongo-keyfile:/etc/mongo-keyfile:ro
    command: [ "mongod", "--replSet", "rs0", "--keyFile", "/etc/mongo-keyfile", "--bind_ip_all" ]

  mongodb-secondary:
    build: ./docker/mongodb
    env_file: .env
    image: grapeshub/mongodb-grapes:latest
    container_name: grapes-mongodb-secondary
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: SparringMASI!
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data_secondary:/data/db
      - ./docker/mongodb/mongo-keyfile:/etc/mongo-keyfile:ro
    command: [ "mongod", "--replSet", "rs0", "--keyFile", "/etc/mongo-keyfile", "--bind_ip_all" ]

  mongodb-arbiter:
    build: ./docker/mongodb
    env_file: .env
    image: grapeshub/mongodb-grapes:latest
    container_name: grapes-mongodb-arbiter
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: SparringMASI!
    ports:
      - "27019:27017"
    volumes:
      - mongodb_data_arbiter:/data/db
      - ./docker/mongodb/mongo-keyfile:/etc/mongo-keyfile:ro
    command: [ "mongod", "--replSet", "rs0", "--keyFile", "/etc/mongo-keyfile", "--bind_ip_all" ]
  ### Exchange
  rabbitmq:
    build: ./docker/rabbitmq
    env_file: .env
    image: mydockerhub/rabbitmq-grapes:latest
    container_name: grapes-rabbitmq
    volumes:
      - ./docker/rabbitmq/volumes/data/:/var/lib/rabbitmq/mnesia
      - ./docker/rabbitmq/volumes/logs/:/var/log/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: grapes
      RABBITMQ_DEFAULT_PASS: grapes
    ports:
      - "5672:5672"
      - "15673:15672"

### MONITORING
  sonarqube:
    image: sonarqube:lts-community
    container_name: grapes-sonarqube
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    ports:
      - "9000:9000"
    depends_on:
      - sonarqube-db

  sonarqube-db:
    image: postgres:13
    container_name: grapes-sonarqube-db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - sonarqube-data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    container_name: grapes-prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grapes-grafana
    volumes:
      - ./monitoring/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    ports:
      - "3000:3000"
    depends_on:
      - prometheus


### BACKEND

  api-gateway:
    build: ./api-gateway
    env_file: .env
    image: grapeshub/api-gateway:latest

    container_name: api-gateway
    ports:
      - "8090:8090"
    depends_on:
      - mongodb-primary
      - mariadb
      - data-mining-service
      - auth-service
      - sales-service
      - payment-service
      - chat-service

  auth-service:
    build: ./auth-service/auth-backend
    env_file: .env
    image: grapeshub/auth-service-backend:latest
    container_name: auth-backend
    ports:
      - "8091:8091"
    depends_on:
      - mongodb-primary
      - mariadb

  sales-service:
    build: ./sales-service
    env_file: .env
    image: grapeshub/sales-service:latest
    container_name: sales-backend
    ports:
      - "8092:8092"
    depends_on:
      - mariadb

  payment-service:
    build: ./payment-service/payment-backend
    env_file: .env
    image: grapeshub/payment-service-backend:latest
    container_name: payment-backend
    ports:
      - "8094:8094"
    depends_on:
      - mariadb

  chat-service:
    build: ./chat-service
    env_file: .env
    image: grapeshub/chat-service:latest
    container_name: chat-backend
    ports:
      - "8095:8095"
    depends_on:
      - mongodb-primary

  data-mining-service:
    build: ./data-mining-service
    image: grapeshub/data-mining-service:latest
    container_name: data-mining-backend
    ports:
      - "8096:8096"
    depends_on:
      - mongodb-primary
      - mariadb

### FRONTEND

  frontend-web:
    build: ./frontend-web
    image: grapeshub/grapes-frontend:latest
    container_name: grapes-frontend
    ports:
      - "3001:80"
    depends_on:
      - api-gateway

  frontend-auth:
    build: ./auth-service/auth-frontend
    image: grapeshub/auth-service-frontend:latest
    container_name: auth-frontend
    ports:
      - "3002:81"
    depends_on:
      - api-gateway

  frontend-payment:
    build: ./payment-service/payment-frontend
    image: grapeshub/payment-service-frontend:latest
    container_name: payment-frontend
    ports:
      - "3003:82"
    depends_on:
      - api-gateway

volumes:
  mariadb_data:
  mongodb_data_primary:
  mongodb_data_secondary:
  mongodb_data_arbiter:
  sonarqube-data:
