version: '3.9'

services:
  mariadb:
    image: ${ORACLE_REGION_ID}.ocir.io/${ORACLE_TENANCY_NAMESPACE}/grapeshub/mariadb-grapes:latest
    container_name: grapes-mariadb
    env_file: .env
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_REPLICATION_USER: ${MARIADB_REPLICATION_USER}
      MARIADB_REPLICATION_PASSWORD: ${MARIADB_REPLICATION_PASSWORD}
      MARIADB_REPLICATION_ROLE: master
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  mongodb:
    image: ${ORACLE_REGION_ID}.ocir.io/${ORACLE_TENANCY_NAMESPACE}/grapeshub/mongodb-grapes:latest
    container_name: grapes-mongodb
    env_file: .env
    platform: linux/arm64
    command: --replSet rs0 --keyFile /data/keyfile --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_USER_RW: ${MONGO_USER_RW}
      MONGO_PASSWORD_RW: ${MONGO_PASSWORD_RW}


  rabbitmq:
    image: ${ORACLE_REGION_ID}.ocir.io/${ORACLE_TENANCY_NAMESPACE}/grapeshub/rabbitmq-grapes:latest
    container_name: rabbitmq
    env_file: .env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
 #Monitoring
  redis:
    image: redis:7.2-alpine
    env_file: .env
    container_name: grapes-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    entrypoint: [ "sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\"" ]

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - auth-service
      - sales-service
      - payment-service
      - chat-service
      - data-mining-service

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    environment:
      SONARQUBE_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonar
      SONARQUBE_JDBC_USERNAME: ${SONARQUBE_JDBC_USERNAME}
      SONARQUBE_JDBC_PASSWORD: ${SONARQUBE_JDBC_PASSWORD}
    ports:
      - "9000:9000"

  sonarqube-db:
    image: postgres:13
    container_name: sonarqube-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  mongodb-exporter:
    image: bitnami/mongodb-exporter:latest
    container_name: mongo-exporter
    restart: always
    environment:
      MONGODB_URI: "mongodb://exporter:exporterpass@grapes-mongodb:27017/admin"
    ports:
      - "9216:9216"
    depends_on:
      - mongodb

  redis-exporter:
    image: oliver006/redis_exporter
    container_name: redis-exporter
    environment:
      REDIS_ADDR: redis://grapes-redis:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - redis
    ports:
      - "9121:9121"

  # Backends & Gateway
  api-gateway:
    image: ${ORACLE_REGION_ID}.ocir.io/${ORACLE_TENANCY_NAMESPACE}/grapeshub/api-gateway:latest
    container_name: api-gateway
    env_file: .env
    ports:
      - "8090:8090"

  auth-service:
    image: ${ORACLE_REGION_ID}.ocir.io/${ORACLE_TENANCY_NAMESPACE}/grapeshub/auth-service-backend:latest
    container_name: auth-backend
    env_file: .env
    ports:
      - "8091:8091"

  sales-service:
    image: ${ORACLE_REGION_ID}.ocir.io/${ORACLE_TENANCY_NAMESPACE}/grapeshub/sales-service:latest
    container_name: sales-backend
    env_file: .env
    ports:
      - "8092:8092"

  payment-service:
    image: ${ORACLE_REGION_ID}.ocir.io/${ORACLE_TENANCY_NAMESPACE}/grapeshub/payment-service-backend:latest
    container_name: payment-backend
    env_file: .env
    ports:
      - "8093:8093"
    volumes:
      - ./keystore:/app/keystore
      - ./generate-keystore.sh:/app/generate-keystore.sh
    entrypoint: >
      sh -c "
        chmod +x /app/generate-keystore.sh &&  
        /app/generate-keystore.sh &&  
        java -jar /app/app.jar  
      "

  chat-service:
    image: ${ORACLE_REGION_ID}.ocir.io/${ORACLE_TENANCY_NAMESPACE}/grapeshub/chat-service:latest
    container_name: chat-backend
    ports:
      - "8094:8094"

  data-mining-service:
    build: ./data-mining-service/data_ingestion_service
    image: ${ORACLE_REGION_ID}.ocir.io/${ORACLE_TENANCY_NAMESPACE}/grapeshub/data-mining-service:latest
    container_name: data-ingestion-service
    restart: unless-stopped
    env_file: .env
    environment:
      - RABBITMQ_HOST=rabbitmq # Use service name
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER} # From .env via env_file
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD} # From .env via env_file
      - AMQP_VHOST=/ # Default VHost usually correct
      - ACTIVITY_LOGS_QUEUE=q_activity_logs # Explicitly set
      - AUTH_LOGS_QUEUE=q.auth_logs

      # --- DB Connection (Using ROOT Credentials) ---
      # MariaDB Root
      - MYSQL_USER=root # Explicitly set to root
      - MYSQL_PWD=${DB_PASSWORD} # Use the ROOT password defined for MariaDB (DB_PASSWORD from .env)
      - MYSQL_HOST=mariadb # Use service name
      - MYSQL_PORT=3306
      - MYSQL_DB_ACTIVITIES=BD_OPER_ACTIVITIES
      - MYSQL_TRANSACTIONS_TABLE=transactions #

      # MongoDB Root
      - MONGO_USER=${MONGO_ROOT_USER} # Use ROOT user from .env
      - MONGO_PWD=${MONGO_ROOT_PASSWORD} # Use ROOT password from .env
      - MONGO_HOST=mongodb # Use service name
      - MONGO_PORT=27017
      - MONGO_DB_AUTH=BD_OPER_PROC_AUTH # Target DB Name for auth logs
      - MONGO_AUTH_SOURCE=admin # Root user is usually defined in 'admin' db
      - MONGO_AUTH_COLLECTION=authentication_logs #

      # --- SQLAlchemy Pool Recycle ---
      - POOL_RECYCLE=${POOL_RECYCLE:-3600} # Use from .env or default

      #       --- Consumer Logic Params (Optional - Override defaults in consumer.py) ---
      #       - SAVE_INTERVAL_SECONDS=60
      #       - MAX_BATCH_SIZE_TRANS=50
      #       - MAX_BATCH_SIZE_AUTH=100
      #       - MAX_HOLD_TIME_SECONDS=120
      #       - LOG_LEVEL=debug

      # --- Python & Other ---
      - PYTHONUNBUFFERED=1 # Good for seeing logs immediately
      - USER=${USER:-unknown} # Usually not needed by script
    ports:
      - "8094:8094"
    depends_on:
      - rabbitmq
      - mariadb
      - mongodb


volumes:
  mariadb_data:
  mongodb_data:
  rabbitmq_data:
  redis_data: