spring.application.name=project2
server.ssl.enabled=true
server.ssl.key-store=classpath:server_keystore.jks
server.ssl.key-store-password=komnoupoueamine
server.ssl.key-store-type=JKS
server.port=8043