global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Métriques VM3 (ARM - Backends & Bases de Données)
  - job_name: 'vm3-backends'
    metrics_path: '/actuator/metrics'  # Chemin spécifique à Spring Boot
    static_configs:
      - targets: [ '172.20.10.3:8090', '172.20.10.3:8092','172.20.10.3:8091' ]

  # Métriques VM1 (x86 - Monitoring & Replicas)
  - job_name: 'vm1-monitoring'
    static_configs:
      - targets:
          - '79.76.110.161:9090'   # Prometheus (auto-surveillance)
          - 'vm1:9100'   # Node Exporter
          - 'vm1:3000'   # Grafana (métriques internes)

  # Métriques VM2 (x86 - Frontends)
  - job_name: 'vm2-frontends'
    static_configs:
      - targets:
          - 'vm2:9100'   # Node Exporter (si déployé)
          - 'vm2:3838'   # Shiny App (si exposé)