package grapes.microservices.paymentbackend.models;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.math.BigDecimal;
import java.time.LocalDate;

class AccountTest {

    @Test
    void noArgsConstructor_createsAccount() {
        // Test the no-argument constructor
        Account account = new Account();
        assertNotNull(account);
        assertNull(account.getAccountNumber()); // Fields should be null initially
    }

    @Test
    void allArgsConstructor_setsAllFields() {
        // Test the all-argument constructor provided by Lombok @AllArgsConstructor
        Client mockClient = new Client(); // Use a simple object or mock for related entities
        mockClient.setId(1L);
        Bank mockBank = new Bank();
        mockBank.setBankName("Mock Bank");
        LocalDate openingDate = LocalDate.now();
        BigDecimal balance = new BigDecimal("1000.50");

        Account account = new Account(
                "BE123456789",
                mockClient,
                mockBank,
                "OTP",
                balance,
                openingDate,
                "Checking",
                "Active"
        );

        // Assert that all fields were set correctly
        assertEquals("BE123456789", account.getAccountNumber());
        assertEquals(mockClient, account.getClient());
        assertEquals(mockBank, account.getBank());
        assertEquals("OTP", account.getAuthenticationType());
        assertEquals(0, balance.compareTo(account.getBalance())); // Use compareTo for BigDecimal
        assertEquals(openingDate, account.getOpeningDate());
        assertEquals("Checking", account.getAccountType());
        assertEquals("Active", account.getStatus());
    }

    @Test
    void gettersAndSetters_workCorrectly() {
        // Test the getters and setters generated by Lombok @Data
        Account account = new Account();
        Client mockClient = new Client();
        mockClient.setId(2L);
        BigDecimal newBalance = new BigDecimal("50.25");
        LocalDate newDate = LocalDate.of(2024, 1, 1);

        // Use setters
        account.setAccountNumber("BE987654321");
        account.setClient(mockClient);
        account.setBalance(newBalance);
        account.setStatus("Closed");
        account.setOpeningDate(newDate);

        // Use getters to verify
        assertEquals("BE987654321", account.getAccountNumber());
        assertEquals(mockClient, account.getClient());
        assertEquals(0, newBalance.compareTo(account.getBalance()));
        assertEquals("Closed", account.getStatus());
        assertEquals(newDate, account.getOpeningDate());
    }
}