package grapes.microservices.paymentbackend.models;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.time.LocalDateTime;

class AuthTokenTest {

    private Client mockClient;
    private String testTokenValue;

    @BeforeEach
    void setUp() {
        // Set up a mock client for tests
        mockClient = new Client();
        mockClient.setId(101L);
        mockClient.setEmail("test@example.com");
        testTokenValue = "123456";
    }

    @Test
    void noArgsConstructor_createsAuthToken() {
        // Test the no-argument constructor
        AuthToken token = new AuthToken();
        assertNotNull(token);
        assertNull(token.getToken());
        assertNull(token.getClient());
    }

    @Test
    void allArgsConstructor_setsAllFields() {
        // Test the all-argument constructor
        LocalDateTime now = LocalDateTime.now();
        LocalDateTime expires = now.plusMinutes(5);

        AuthToken token = new AuthToken(1L, testTokenValue, now, expires, false, mockClient);

        assertEquals(1L, token.getId());
        assertEquals(testTokenValue, token.getToken());
        assertEquals(now, token.getCreatedAt());
        assertEquals(expires, token.getExpiresAt());
        assertFalse(token.isUsed());
        assertEquals(mockClient, token.getClient());
    }

    @Test
    void customConstructor_initializesCorrectly() {
        // Test the custom constructor used for generating new tokens
        AuthToken token = new AuthToken(testTokenValue, mockClient);

        assertNull(token.getId()); // ID is generated by persistence layer
        assertEquals(testTokenValue, token.getToken());
        assertEquals(mockClient, token.getClient());
        assertNotNull(token.getCreatedAt());
        assertNotNull(token.getExpiresAt());
        // Check that expiresAt is roughly 3 minutes after createdAt
        assertTrue(token.getExpiresAt().isAfter(token.getCreatedAt().plusMinutes(2).plusSeconds(55)));
        assertTrue(token.getExpiresAt().isBefore(token.getCreatedAt().plusMinutes(3).plusSeconds(5)));
        assertFalse(token.isUsed()); // Should default to false
    }

    @Test
    void isValid_shouldReturnTrue_forNewUnusedToken() {
        // Test isValid() for a newly created token
        AuthToken token = new AuthToken(testTokenValue, mockClient);
        // Ensure expiresAt is in the future and isUsed is false (defaults from constructor)
        assertTrue(token.isValid(), "Newly created token should be valid");
    }

    @Test
    void isValid_shouldReturnFalse_whenTokenIsUsed() {
        // Test isValid() when the token has been marked as used
        AuthToken token = new AuthToken(testTokenValue, mockClient);
        token.setUsed(true); // Manually mark as used
        token.setExpiresAt(LocalDateTime.now().plusMinutes(1)); // Ensure it's not expired

        assertFalse(token.isValid(), "Used token should not be valid");
    }

    @Test
    void isValid_shouldReturnFalse_whenTokenIsExpired() {
        // Test isValid() when the token's expiration time has passed
        AuthToken token = new AuthToken(testTokenValue, mockClient);
        token.setUsed(false); // Ensure it's not used
        token.setExpiresAt(LocalDateTime.now().minusSeconds(1)); // Set expiration in the past

        assertFalse(token.isValid(), "Expired token should not be valid");
    }

    @Test
    void isValid_shouldReturnFalse_whenTokenIsUsedAndExpired() {
        // Test isValid() when the token is both used and expired
        AuthToken token = new AuthToken(testTokenValue, mockClient);
        token.setUsed(true);
        token.setExpiresAt(LocalDateTime.now().minusSeconds(1));

        assertFalse(token.isValid(), "Used and expired token should not be valid");
    }
}