package grapes.microservices.paymentbackend.models;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class BankTest {

    @Test
    void noArgsConstructor_createsBank() {
        // Test the no-argument constructor
        Bank bank = new Bank();
        assertNotNull(bank);
        assertNull(bank.getBankName()); // Fields should be null initially
        assertNull(bank.getBankAddress());
        assertNull(bank.getCountry());
    }

    @Test
    void allArgsConstructor_setsAllFields() {
        // Test the all-argument constructor
        String bankName = "Test Bank Inc.";
        String address = "123 Banking St, Financial City";
        String country = "Testland";

        Bank bank = new Bank(bankName, address, country);

        // Assert that all fields were set correctly
        assertEquals(bankName, bank.getBankName());
        assertEquals(address, bank.getBankAddress());
        assertEquals(country, bank.getCountry());
    }

    @Test
    void gettersAndSetters_workCorrectly() {
        // Test the getters and setters generated by Lombok @Data
        Bank bank = new Bank();
        String newBankName = "Global Finance";
        String newAddress = "456 Currency Ave";
        String newCountry = "Cashland";

        // Use setters
        bank.setBankName(newBankName);
        bank.setBankAddress(newAddress);
        bank.setCountry(newCountry);

        // Use getters to verify
        assertEquals(newBankName, bank.getBankName());
        assertEquals(newAddress, bank.getBankAddress());
        assertEquals(newCountry, bank.getCountry());
    }
}