package grapes.microservices.paymentbackend.models;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.time.LocalDate;

class CardTest {

    private Client mockClient;
    private String testCardNumber;
    private String testExpirationDate;
    private String testCardholderName;

    @BeforeEach
    void setUp() {
        // Set up a mock client for tests
        mockClient = new Client();
        mockClient.setId(202L);
        testCardNumber = "1234567890123456";
        testExpirationDate = "12/2028";
        testCardholderName = "John Doe";
    }

    @Test
    void noArgsConstructor_createsCard() {
        // Test the no-argument constructor
        Card card = new Card();
        assertNotNull(card);
        assertNull(card.getCardNumber());
        assertNull(card.getClient());
    }

    @Test
    void allArgsConstructor_setsAllFields() {
        // Test the all-argument constructor (including fields not set by custom constructor)
        LocalDate addedDate = LocalDate.now().minusDays(1);
        Card card = new Card(
                1L,
                mockClient,
                testCardNumber,
                testExpirationDate,
                testCardholderName,
                "VISA",
                "inactive",
                addedDate
        );

        assertEquals(1L, card.getId());
        assertEquals(mockClient, card.getClient());
        assertEquals(testCardNumber, card.getCardNumber());
        assertEquals(testExpirationDate, card.getExpirationDate());
        assertEquals(testCardholderName, card.getCardholderName());
        assertEquals("VISA", card.getCardType());
        assertEquals("inactive", card.getStatus());
        assertEquals(addedDate, card.getAddedDate());
    }

    @Test
    void customConstructor_initializesCorrectlyWithDefaults() {
        // Test the custom constructor used for creating new cards
        Card card = new Card(mockClient, testCardNumber, testExpirationDate, testCardholderName);

        assertNull(card.getId()); // ID is generated by persistence layer
        assertEquals(mockClient, card.getClient());
        assertEquals(testCardNumber, card.getCardNumber());
        assertEquals(testExpirationDate, card.getExpirationDate());
        assertEquals(testCardholderName, card.getCardholderName());
        assertEquals("active", card.getStatus()); // Check default status
        assertNotNull(card.getAddedDate()); // Check addedDate is set
        assertTrue(card.getAddedDate().isEqual(LocalDate.now()) || card.getAddedDate().isBefore(LocalDate.now().plusDays(1))); // Check it's today
        assertNull(card.getCardType()); // Card type is not set by this constructor
    }

    @Test
    void getMaskedCardNumber_masksCorrectly_forStandardLength() {
        // Test masking for a 16-digit card
        Card card = new Card(mockClient, testCardNumber, testExpirationDate, testCardholderName);
        assertEquals("************3456", card.getMaskedCardNumber());
    }

    @Test
    void getMaskedCardNumber_masksCorrectly_forShorterLength() {
        // Test masking for a 13-digit card
        String shortCardNumber = "1234567890123";
        Card card = new Card(mockClient, shortCardNumber, testExpirationDate, testCardholderName);
        // Should still show only the last 4 digits
        assertEquals("************0123", card.getMaskedCardNumber());
    }

    @Test
    void getMaskedCardNumber_returnsAsterisks_forVeryShortLength() {
        // Test masking for card number < 4 digits
        String veryShortCardNumber = "123";
        Card card = new Card(mockClient, veryShortCardNumber, testExpirationDate, testCardholderName);
        assertEquals("****", card.getMaskedCardNumber());
    }

    @Test
    void getMaskedCardNumber_returnsAsterisks_forNullCardNumber() {
        // Test masking when card number is null
        Card card = new Card(mockClient, null, testExpirationDate, testCardholderName);
        assertEquals("****", card.getMaskedCardNumber());
    }

    @Test
    void getMaskedCardNumber_returnsAsterisks_forEmptyCardNumber() {
        // Test masking when card number is empty
        Card card = new Card(mockClient, "", testExpirationDate, testCardholderName);
        assertEquals("****", card.getMaskedCardNumber());
    }
}