package grapes.microservices.paymentbackend.models;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.ArrayList; // Needed for collections in AllArgsConstructor test

class ClientTest {

    @Test
    void noArgsConstructor_createsClient() {
        // Test the no-argument constructor
        Client client = new Client();
        assertNotNull(client);
        assertNull(client.getId());
        assertNull(client.getEmail());
    }

    @Test
    void allArgsConstructor_setsAllFields() {
        // Test the all-argument constructor
        LocalDate birthDate = LocalDate.of(1990, 5, 15);
        LocalDate regDate = LocalDate.now();
        BigDecimal salary = new BigDecimal("55000.75");

        Client client = new Client(
                1L, "Smith", "Jane", "Female", birthDate, "Married",
                salary, "jane.smith@example.com", "hashedPassword",
                "NRN123456", "+15551234567", "123 Main St, Anytown",
                regDate, "Active", new ArrayList<>(), new ArrayList<>()
        );

        // Assert that all fields were set correctly
        assertEquals(1L, client.getId());
        assertEquals("Smith", client.getLastName());
        assertEquals("Jane", client.getFirstName());
        assertEquals("Female", client.getGender());
        assertEquals(birthDate, client.getBirthDate());
        assertEquals("Married", client.getMaritalStatus());
        assertEquals(0, salary.compareTo(client.getAverageMonthlySalary()));
        assertEquals("jane.smith@example.com", client.getEmail());
        assertEquals("hashedPassword", client.getPassword());
        assertEquals("NRN123456", client.getNationalRegistryNumber());
        assertEquals("+15551234567", client.getPhoneNumber());
        assertEquals("123 Main St, Anytown", client.getAddress());
        assertEquals(regDate, client.getRegistrationDate());
        assertEquals("Active", client.getStatus());
        assertNotNull(client.getAccounts()); // Check collections are initialized
        assertNotNull(client.getCards());
        assertTrue(client.getAccounts().isEmpty());
        assertTrue(client.getCards().isEmpty());
    }

    @Test
    void gettersAndSetters_workCorrectly() {
        // Test the getters and setters generated by Lombok @Data
        Client client = new Client();
        String newEmail = "new.email@example.com";
        String newPhone = "+447700900000";
        String newStatus = "Suspended";

        // Use setters
        client.setId(2L);
        client.setEmail(newEmail);
        client.setPhoneNumber(newPhone);
        client.setStatus(newStatus);
        client.setFirstName("Peter");
        client.setLastName("Jones");

        // Use getters to verify
        assertEquals(2L, client.getId());
        assertEquals(newEmail, client.getEmail());
        assertEquals(newPhone, client.getPhoneNumber());
        assertEquals(newStatus, client.getStatus());
        assertEquals("Peter", client.getFirstName());
        assertEquals("Jones", client.getLastName());
    }

    @Test
    void getFullName_returnsCorrectFormat() {
        // Test the custom getFullName method
        Client client = new Client();
        client.setFirstName("Alice");
        client.setLastName("Wonder");

        assertEquals("Alice Wonder", client.getFullName());
    }

    @Test
    void getFullName_handlesNullFirstName() {
        // Test getFullName when first name is null
        Client client = new Client();
        client.setFirstName(null);
        client.setLastName("Smith");

        assertEquals("null Smith", client.getFullName()); // Default behavior of string concatenation with null
    }

    @Test
    void getFullName_handlesNullLastName() {
        // Test getFullName when last name is null
        Client client = new Client();
        client.setFirstName("Bob");
        client.setLastName(null);

        assertEquals("Bob null", client.getFullName()); // Default behavior
    }

    @Test
    void getFullName_handlesNullFirstAndLastName() {
        // Test getFullName when both names are null
        Client client = new Client();
        client.setFirstName(null);
        client.setLastName(null);

        assertEquals("null null", client.getFullName()); // Default behavior
    }
}