package grapes.microservices.paymentbackend.models;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.time.LocalDate;

class MerchantTest {

    @Test
    void noArgsConstructor_createsMerchant() {
        // Test the no-argument constructor
        Merchant merchant = new Merchant();
        assertNotNull(merchant);
        assertNull(merchant.getMerchantName()); // Fields should be null initially
        assertNull(merchant.getVatNumber());
    }

    @Test
    void allArgsConstructor_setsAllFields() {
        // Test the all-argument constructor
        String merchantName = "SuperMart";
        String sector = "Retail";
        String address = "1 Market Square";
        String vat = "VAT123456789";
        LocalDate regDate = LocalDate.of(2020, 1, 10);
        String status = "Active";

        Merchant merchant = new Merchant(
                merchantName,
                sector,
                address,
                vat,
                regDate,
                status
        );

        // Assert that all fields were set correctly
        assertEquals(merchantName, merchant.getMerchantName());
        assertEquals(sector, merchant.getBusinessSector());
        assertEquals(address, merchant.getMerchantAddress());
        assertEquals(vat, merchant.getVatNumber());
        assertEquals(regDate, merchant.getRegistrationDate());
        assertEquals(status, merchant.getMerchantStatus());
    }

    @Test
    void gettersAndSetters_workCorrectly() {
        // Test the getters and setters generated by Lombok @Data
        Merchant merchant = new Merchant();
        String newName = "Online Books";
        String newSector = "E-commerce";
        String newStatus = "Pending";
        LocalDate newDate = LocalDate.now();

        // Use setters
        merchant.setMerchantName(newName);
        merchant.setBusinessSector(newSector);
        merchant.setMerchantStatus(newStatus);
        merchant.setRegistrationDate(newDate);
        merchant.setVatNumber("VAT987654");
        merchant.setMerchantAddress("Web Address");

        // Use getters to verify
        assertEquals(newName, merchant.getMerchantName());
        assertEquals(newSector, merchant.getBusinessSector());
        assertEquals(newStatus, merchant.getMerchantStatus());
        assertEquals(newDate, merchant.getRegistrationDate());
        assertEquals("VAT987654", merchant.getVatNumber());
        assertEquals("Web Address", merchant.getMerchantAddress());
    }
}