server.port=${PAYMENT_SERVICE_PORT}
spring.application.name=payment-backend

#MariaDB
spring.datasource.url=${PAYMENT_DB_URL}
spring.datasource.username=${PAYMENT_DB_USER}
spring.datasource.password=${PAYMENT_DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.contexts=grapes
