spring.application.name=payment-backend
server.ssl.enabled=false
server.ssl.key-store=classpath:server_keystore.jks
server.ssl.key-store-password=komnoupoueamine
server.ssl.key-store-type=JKS
server.port=8043

# Database Configuration - MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3306/paymentdb
spring.datasource.driverClassName=org.mariadb.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=SparringMASI!
spring.jpa.database-platform=org.hibernate.dialect.MariaDB106Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Twilio Configuration
twilio.account.sid=AC14fb328ceb78103dbac1c775f01751e7
twilio.auth.token=9606902cc7b38ce555a8814119fc7da7
twilio.phone.number=+32492088935

# Keystore Configuration
keystore.client.path=src/main/resources/keystore/client_keystore.jks
keystore.client.password=komnoupoueamine
keystore.client.alias=client
keystore.client.truststore=src/main/resources/keystore/client_truststore.jks

# Password Security
password.salt=HIARD

spring.liquibase.enabled=false


