
spring.application.name=chat-service
server.port=${CHAT_SERVICE_PORT}
spring.data.mongodb.uri=${CHAT_MONGO_URI}
spring.data.mongodb.database=${CHAT_MONGO_DB}
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

pusher.app_id=${PUSHER_APP_ID}
pusher.key=${PUSHER_APP_KEY}
pusher.secret=${PUSHER_SECRET}
pusher.cluster=${PUSHER_CLUSTER}
pusher.encrypted=true

