
spring.application.name=chat-service
server.port=${CHAT_SERVICE_PORT}
spring.data.mongodb.uri=${CHAT_MONGO_URI}
spring.data.mongodb.database=${CHAT_MONGO_DB}
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

## Monitoring
management.endpoints.web.exposure.include=*
management.metrics.tags.service=api-service