
spring.application.name=chat-service
server.port=${CHAT_SERVICE_PORT}
spring.data.mongodb.uri=${CHAT_MONGO_URI}
spring.data.mongodb.database=${CHAT_MONGO_DB}
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}


spring.rabbitmq.exchange.name=${RABBITMQ_EXCHANGE_NAME}
spring.rabbitmq.queue.prefix=${RABBITMQ_QUEUE_PREFIX}
spring.rabbitmq.routing.key.prefix=${RABBITMQ_ROUTING_KEY_PREFIX}


#for debug
spring.rabbitmq.template.retry.enabled=true
spring.rabbitmq.template.mandatory=true
spring.rabbitmq.publisher-returns=true
spring.rabbitmq.publisher-confirm-type=correlated
logging.level.org.springframework.amqp=DEBUG
