server.port=8092
spring.application.name=sales-service


# Mariadb
spring.datasource.url=jdbc:mariadb://localhost:3306/sales_db
spring.datasource.username=root
spring.datasource.password=SparringMASI!
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.datasource.url=jdbc:mariadb://grapes-mariadb:3306/sales_db


# Liquibase
spring.liquibase.enabled=true
spring.liquibase.contexts=grapes
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

spring.jackson.serialization.indent_output=true


logging.level.org.hibernate=DEBUG
logging.level.org.hibernate.validator=TRACE
server.error.include-message=always
server.error.include-binding-errors=always
logging.level.org.springframework.web=DEBUG


