server.port=8092
spring.application.name=sales-service


# Mariadb
spring.datasource.url=jdbc:mariadb://localhost:3306/sales_db
spring.datasource.username=root
spring.datasource.password=SparringMASI!
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.contexts=grapes
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
