spring.application.name=sales-service
server.port=${SALES_SERVICE_PORT}


# MariaDB
spring.datasource.url=${SALES_DB_URL}
spring.datasource.username=${SALES_DB_USER}
spring.datasource.password=${SALES_DB_PASSWORD}


# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.contexts=grapes

#THIS CODE NOT FOR PRODUCTION
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
spring.jackson.serialization.indent_output=true
logging.level.org.hibernate=DEBUG
logging.level.org.hibernate.validator=TRACE
server.error.include-message=always
server.error.include-binding-errors=always
logging.level.org.springframework.web=DEBUG
#TO REMOVE FOR PRODUCTION


spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}



# Retry settings for RabbitMQ consumer startup
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=10
spring.rabbitmq.listener.simple.retry.initial-interval=3000
spring.rabbitmq.listener.simple.retry.multiplier=2.0
spring.rabbitmq.listener.simple.retry.max-interval=10000


#for debug
spring.rabbitmq.template.retry.enabled=true
spring.rabbitmq.template.mandatory=true
spring.rabbitmq.publisher-returns=true
spring.rabbitmq.publisher-confirm-type=correlated

# Redis configuration
spring.cache.type=redis

# Redis Configuration
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
<<<<<<< HEAD
=======
spring.data.redis.password=${REDIS_PASSWORD}
>>>>>>> origin/sprint-4
spring.cache.redis.time-to-live=${REDIS_TTL}

spring.web.resources.static-locations=file:uploads/



spring.web.resources.static-locations=file:uploads/


## Monitoring
management.endpoints.web.exposure.include=*
management.metrics.tags.service=sales-service