// TokenDTO.java
package grapes.microservices.paymentbackend.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO for payment token information transfer between application layers.
 * Contains the unique identifier for a payment token used in transaction processing.
 * This token is typically generated by a payment gateway or processor.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class TokenDTO {
    // Unique identifier for the token
    private String paymentToken;
}