name: Build, Test, Push & Deploy (Docker)

on:
  workflow_dispatch:  # Allows you to manually launch

permissions:
  id-token: write
  contents: read
jobs:
  build:
    name: Build Microservices
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🛠️ Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

        # DskipTests to skip running tests during the build process.
      - name: "🔍 Build API Gateway"
        run: mvn -B clean install -DskipTests --file api-gateway/pom.xml

      - name: "🔍 Build Auth Service"
        run: mvn -B clean install -DskipTests --file auth-service/auth-backend/pom.xml

      - name: "🔍 Build Chat Service"
        run: mvn -B clean install -DskipTests --file chat-service/pom.xml

      - name: "🔍 Build Payment Service"
        run: mvn -B clean install -DskipTests --file payment-service/payment-backend/pom.xml

      - name: "🔍 Build Sales Service"
        run: mvn -B clean install -DskipTests --file sales-service/pom.xml

      - name: 🐍 Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: "🧪 Install dependencies for Python Microservices"
        run: pip install -r data-mining-service/requirements.txt

      ## FRONTEND
      - name: 🌐 Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: "📦 Install Frontend Dependencies"
        run: |
          cd frontend-web
          npm install
  

  test :
    name: Test Microservices
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🛠️ Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: "🔍 Run Tests for API Gateway"
        run: mvn -B test --file api-gateway/pom.xml

      - name: "🔍 Run Tests for Auth Service"
        run: mvn -B test --file auth-service/auth-backend/pom.xml

      - name: "🔍 Run Tests for Chat Service"
        run: mvn -B test --file chat-service/pom.xml

      - name: "🔍 Run Tests for Payment Service"
        run: mvn -B test --file payment-service/payment-backend/pom.xml

#      - name: "🔍 Run Tests for Sales Service"
#        run: mvn -B test --file sales-service/pom.xml

      - name: 🐍 Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

#      - name: 🧪 Run Tests for Python Microservices
#        run: pytest data-mining-service/tests

#      ## FRONTEND
#      - name: 🌐 Install Node.js
#        uses: actions/setup-node@v3
#        with:
#          node-version: 18
#
#      - name: 🧪 Run Frontend Tests
#        run: |
#          npm run test

  docker-build-and-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    needs:
      - build
      - test

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login via OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR
        run: |
          az acr login --name grapeshub

      - name: Build and Push Docker Image
        run: |
          compose build mariadb
          docker compose push mariadb

#          docker-compose build mariadb mongodb rabbitmq api-gateway auth-service sales-service payment-service chat-service data-mining-service frontend-web frontend-auth frontend-payment
#          docker-compose push mariadb mongodb rabbitmq api-gateway auth-service sales-service payment-service chat-service data-mining-service frontend-web frontend-auth frontend-payment

#  deploy:
#    name: Deploy on Azure VM (Manual)
#    runs-on: ubuntu-latest
#    needs:
#      - build
#      - tests
#    if: github.event_name == 'workflow_dispatch'  # Launches only if manual
#
#    steps:
#      - name: 📥 Checkout repository
#        uses: actions/checkout@v3
#
#      - name: 🔑 SSH into Azure VM and Deploy
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.AZURE_VM_IP }}
#          username: ${{ secrets.AZURE_VM_USER }}
#          key: ${{ secrets.AZURE_VM_SSH_KEY }}
#          script: |
#            cd grapes-microservices  # Path to project
#            git pull origin main  # Update project
#            docker-compose pull  # get new images from registry(grapes hub)
#            docker-compose down
#            docker-compose up -d
