name: Run Tests

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # 🔹 Test Auth (Spring Boot)
      - name: Run Tests for Auth Service (Java)
        working-directory: ./auth-service/auth-backend
        run: mvn clean test

      # 🔹 Test  Sales (Spring Boot)
      - name: Run Tests for Transactions Service (Node.js)
        working-directory: ./transactions-service
        run: mvn clean test
