name: Run Tests

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          service: [auth-service, sales-service, payment-service]
          include:
            - service: auth-service
              test_command: mvn clean test
            - service: sales-service
              test_command: mvn clean test
            - service: payment-service
              test_command: mvn clean test

    steps:
        - name: Checkout repository
          uses: actions/checkout@v3
  
        - name: Run Tests for ${{ matrix.service }}
          working-directory: ./${{ matrix.service }}
          run: ${{ matrix.test_command }}
  

